name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Build
      run: |
        go vet .
        for file in $(find . --name '*.go'  | grep -v /vendor/); do \
          golint $$file; \
        done
        gofmt -w *.go $$(ls -d */ | grep -v /vendor/)
        go env -w GOPRIVATE=github.com/wambozi/*
        export GOFLAGS="-mod=vendor"
        CGO_ENABLED=0 GOOS=linux go build -mod vendor -o ${OUT}-${VERSION} -ldflags="-extldflags \"-static\" -w -s -X main.version=${VERSION}"
