name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Build
      run: |
        export ELASTICSEARCH_IP="172.10.0.2"
        make test-ci
